// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjObMLiCD0uxmrqgMTncrBUcuJVv29iU',
    appId: '1:569444382878:web:982d70056ed60f36aae38f',
    messagingSenderId: '569444382878',
    projectId: 'mnr-telecom',
    authDomain: 'mnr-telecom.firebaseapp.com',
    storageBucket: 'mnr-telecom.firebasestorage.app',
    measurementId: 'G-RLLF3BPPJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy2LcQrofA-p65FVwss-Etjk51XoY1W9o',
    appId: '1:569444382878:android:4fe8966871a5f520aae38f',
    messagingSenderId: '569444382878',
    projectId: 'mnr-telecom',
    storageBucket: 'mnr-telecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASneSXKOyHU2x3dfjF9JfHD-8PvbGy-Qw',
    appId: '1:569444382878:ios:207e9a4c91fdd208aae38f',
    messagingSenderId: '569444382878',
    projectId: 'mnr-telecom',
    storageBucket: 'mnr-telecom.firebasestorage.app',
    iosClientId: '569444382878-qi9h3gooi1u5nevci1qt8ufjkkle8q9r.apps.googleusercontent.com',
    iosBundleId: 'com.conexia.mnr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASneSXKOyHU2x3dfjF9JfHD-8PvbGy-Qw',
    appId: '1:569444382878:ios:207e9a4c91fdd208aae38f',
    messagingSenderId: '569444382878',
    projectId: 'mnr-telecom',
    storageBucket: 'mnr-telecom.firebasestorage.app',
    iosClientId: '569444382878-qi9h3gooi1u5nevci1qt8ufjkkle8q9r.apps.googleusercontent.com',
    iosBundleId: 'com.conexia.mnr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWjObMLiCD0uxmrqgMTncrBUcuJVv29iU',
    appId: '1:569444382878:web:ed77ac539f06d191aae38f',
    messagingSenderId: '569444382878',
    projectId: 'mnr-telecom',
    authDomain: 'mnr-telecom.firebaseapp.com',
    storageBucket: 'mnr-telecom.firebasestorage.app',
    measurementId: 'G-NQ75HEFDLJ',
  );
}
